[package]
name = "pallet-cosmos-x-auth-migrations"
license = "Apache-2.0"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
cosmos-sdk-proto = { workspace = true }
pallet-cosmos-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
nostd = { workspace = true }

[features]
default = ["std"]
std = [
    "cosmos-sdk-proto/std",
    "pallet-cosmos-types/std",
    "serde/std",
    "serde_json/std",
    "nostd/std",
]
