[package]
name = "pallet-cosmos-x-bank-types"
license = "GPL-3.0-or-later"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
cosmos-sdk-proto = { workspace = true }
nostd = { workspace = true }
pallet-cosmos-types = { workspace = true }
pallet-cosmos-x-auth-migrations = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[features]
default = ["std"]
std = [
	"cosmos-sdk-proto/std",
	"nostd/std",
	"pallet-cosmos-types/std",
	"pallet-cosmos-x-auth-migrations/std",
	"serde/std",
]
