[package]
name = "pallet-cosmos-x-bank-types"
version = "0.4.0"
authors = ["Haderech Pte. Ltd."]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noirhq/noir.git"
publish = false

[dependencies]
cosmos-sdk-proto = { version = "0.24.0", default-features = false }
pallet-cosmos-types = { workspace = true, default-features = false }
pallet-cosmos-x-auth-migrations = { workspace = true, default-features = false }
serde = { version = "1.0.210", default-features = false }

[features]
default = ["std"]
std = [
	"cosmos-sdk-proto/std",
	"pallet-cosmos-types/std",
	"pallet-cosmos-x-auth-migrations/std",
	"serde/std",
]
