[workspace]
resolver = "2"
members = [
	"core-primitives",
	"frame/babel",
	"frame/multimap",
	"primitives/cosmos",
	"primitives/ethereum",
	"primitives/runtime",
]

[workspace.dependencies]
frame-babel = { path = "frame/babel", default-features = false }
noir-core-primitives = { path = "core-primitives", default-features = false }
np-cosmos = { path = "primitives/cosmos", default-features = false }
np-ethereum = { path = "primitives/ethereum", default-features = false }
np-runtime = { path = "primitives/runtime", default-features = false }
pallet-multimap = { path = "frame/multimap", default-features = false }

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"

lto = "fat"
codegen-units = 1
