[workspace]
resolver = "2"

members = [
	"core-primitives",
	"primitives/crypto",
	"primitives/runtime",
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"

lto = "fat"
codegen-units = 1
