[workspace]
resolver = "2"
members = [
	"core-primitives",
	"composable/composable-support",
	"composable/vm",
	"composable/vm-wasmi",
	"cosmwasm/std",
	"frame/babel",
	"frame/cosmos",
	"frame/cosmos/types",
	"frame/cosmos/rpc",
	"frame/cosmos/runtime-api",
	"frame/cosmos/x/auth",
	"frame/cosmos/x/auth/migrations",
	"frame/cosmos/x/auth/signing",
	"frame/cosmos/x/bank",
	"frame/cosmos/x/bank/types",
	"frame/cosmos/x/wasm/types",
	"frame/cosmwasm/runtime-api",
	"frame/multimap",
	"primitives/cosmos",
	"primitives/ethereum",
	"primitives/runtime",
	"runtime/common",
	"ziggurat/node",
	"ziggurat/runtime",
]

[workspace.dependencies]
composable-support = { path = "composable/composable-support", default-features = false }
cosmos-rpc = { path = "frame/cosmos/rpc", default-features = false }
cosmos-runtime-api = { path = "frame/cosmos/runtime-api", default-features = false }
cosmwasm-runtime-api = { path = "frame/cosmwasm/runtime-api", default-features = false }
cosmwasm-std = { path = "cosmwasm/std", default-features = false }
cosmwasm-vm = { path = "composable/vm", default-features = false }
cosmwasm-vm-wasmi = { path = "composable/vm-wasmi", default-features = false }
frame-babel = { path = "frame/babel", default-features = false }
noir-core-primitives = { path = "core-primitives", default-features = false }
noir-runtime-common = { path = "runtime/common", default-features = false }
np-cosmos = { path = "primitives/cosmos", default-features = false }
np-ethereum = { path = "primitives/ethereum", default-features = false }
np-runtime = { path = "primitives/runtime", default-features = false }
pallet-cosmos = { path = "frame/cosmos", default-features = false }
pallet-cosmos-types = { path = "frame/cosmos/types", default-features = false }
pallet-cosmos-x-auth = { path = "frame/cosmos/x/auth", default-features = false }
pallet-cosmos-x-auth-migrations = { path = "frame/cosmos/x/auth/migrations", default-features = false }
pallet-cosmos-x-auth-signing = { path = "frame/cosmos/x/auth/signing", default-features = false }
pallet-cosmos-x-bank = { path = "frame/cosmos/x/bank", default-features = false }
pallet-cosmos-x-bank-types = { path = "frame/cosmos/x/bank/types", default-features = false }
pallet-cosmos-x-wasm-types = { path = "frame/cosmos/x/wasm/types", default-features = false }
pallet-multimap = { path = "frame/multimap", default-features = false }

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"

lto = "fat"
codegen-units = 1
