[package]
name = "noir-core-primitives"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/noir-protocol/noir/"

[dependencies]

[features]
default = ["std"]
std = [
]
