[package]
name = "pallet-cosmos-types"
version = "0.4.0"
authors = ["Haderech Pte. Ltd."]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noirhq/noir.git"
publish = false

[dependencies]
bech32 = { version = "0.11", default-features = false, features = ["alloc"] }
cosmos-sdk-proto = { version = "0.24", default-features = false, features = ["cosmwasm"] }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }
impl-trait-for-tuples = { version = "0.2.2" }
parity-scale-codec = { version = "3.6", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.11", default-features = false, features = [
	"derive",
] }
serde = { version = "1.0.210", default-features = false, features = ["derive"] }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }

[dev-dependencies]
hex = { version = "0.4.3", default-features = false }

[features]
default = ["std"]
std = [
	"bech32/std",
	"cosmos-sdk-proto/std",
	"frame-support/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde/std",
	"sp-runtime/std",
	"hex/std",
]
