[package]
name = "pallet-cosmos-types"
license = "Apache-2.0"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
bech32 = { workspace = true, features = ["alloc"] }
cosmos-sdk-proto = { workspace = true, features = ["cosmwasm"] }
frame-support = { workspace = true }
impl-trait-for-tuples = { workspace = true }
nostd = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
sp-runtime = { workspace = true }

[dev-dependencies]
const-hex = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	"bech32/std",
	"cosmos-sdk-proto/std",
	"frame-support/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde/std",
	"sp-runtime/std",
]
