[package]
name = "np-crypto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noir-protocol/noir/"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", optional = true, features = ["derive"] }
sp-core = { version = "7.0.0", default-features = false }
sp-runtime-interface = { version = "7.0.0", default-features = false }
sp-std = { version = "5.0.0", default-features = false }
substrate-bip39 = { version = "0.4.4", optional = true }
tiny-bip39 = { version = "1.0.0", optional = true }

# full crypto
array-bytes = { version = "4.1", optional = true }
p256 = { version = "0.12.0", default-features = false, features = ["ecdsa", "alloc"], optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = [
	"full_crypto",
	"codec/std",
	"scale-info/std",
	"serde",
	"sp-core/std",
	"sp-std/std",
	"substrate-bip39",
	"tiny-bip39",
	"p256/std",
]
full_crypto = [
	"array-bytes",
	"p256",
	"sp-core/full_crypto",
]
