[package]
name = "pallet-cosmos-x-wasm"
version = "0.4.0"
authors = ["Haderech Pte. Ltd."]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noirhq/noir.git"
publish = false

[dependencies]
core2 = { version = "0.4.0", default-features = false, features = ["alloc"] }
cosmos-sdk-proto = { version = "0.24", default-features = false, features = [
	"cosmwasm",
] }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }
hex = { version = "0.4.3", default-features = false }
libflate = { version = "2.1.0", default-features = false }
log = { version = "0.4.21", default-features = false }
pallet-cosmos = { workspace = true, default-features = false }
pallet-cosmos-types = { workspace = true, default-features = false }
pallet-cosmos-x-wasm-types = { workspace = true, default-features = false }
pallet-cosmwasm = { workspace = true, default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }

[features]
default = ["std"]
std = [
	"core2/std",
	"cosmos-sdk-proto/std",
	"frame-support/std",
	"hex/std",
	"libflate/std",
	"log/std",
	"pallet-cosmos/std",
	"pallet-cosmos-types/std",
	"pallet-cosmos-x-wasm-types/std",
	"pallet-cosmwasm/std",
	"sp-core/std",
	"sp-runtime/std",
]
