[package]
name = "pallet-cosmos-x-wasm"
license = "Apache-2.0"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
core2 = { workspace = true, features = ["alloc"] }
cosmos-sdk-proto = { workspace = true, features = ["cosmwasm"] }
frame-support = { workspace = true }
const-hex = { workspace = true }
libflate = { workspace = true }
log = { workspace = true }
pallet-cosmos = { workspace = true }
pallet-cosmos-types = { workspace = true }
pallet-cosmos-x-wasm-types = { workspace = true }
pallet-cosmwasm = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"core2/std",
	"cosmos-sdk-proto/std",
	"frame-support/std",
	"const-hex/std",
	"libflate/std",
	"log/std",
	"pallet-cosmos/std",
	"pallet-cosmos-types/std",
	"pallet-cosmos-x-wasm-types/std",
	"pallet-cosmwasm/std",
	"sp-core/std",
	"sp-runtime/std",
]
