[package]
name = "pallet-cosmos-x-auth"
license = "Apache-2.0"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
cosmos-sdk-proto = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
nostd = { workspace = true }
np-cosmos = { workspace = true }
pallet-cosmos = { workspace = true }
pallet-cosmos-types = { workspace = true }
pallet-cosmos-x-auth-signing = { workspace = true }
ripemd = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }

[dev-dependencies]
const-hex = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	"cosmos-sdk-proto/std",
	"frame-support/std",
	"frame-system/std",
	"np-cosmos/std",
	"pallet-cosmos/std",
	"pallet-cosmos-types/std",
	"pallet-cosmos-x-auth-signing/std",
	"ripemd/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
]
