[package]
name = "pallet-cosmos-x-auth"
version = "0.4.0"
authors = ["Haderech Pte. Ltd."]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noirhq/noir.git"
publish = false

[dependencies]
cosmos-sdk-proto = { version = "0.24.0", default-features = false }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }
np-cosmos = { workspace = true, default-features = false }
pallet-cosmos-x-auth-signing = { workspace = true, default-features = false }
pallet-cosmos = { workspace = true, default-features = false }
pallet-cosmos-types = { workspace = true, default-features = false }
ripemd = { version = "0.1.3", default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407", default-features = false }

[dev-dependencies]
hex = { version = "0.4.3", default-features = false }

[features]
default = ["std"]
std = [
    "cosmos-sdk-proto/std",
    "frame-support/std",
    "frame-system/std",
    "np-cosmos/std",
    "pallet-cosmos-x-auth-signing/std",
    "pallet-cosmos/std",
    "pallet-cosmos-types/std",
    "ripemd/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "hex/std",
]
