[package]
authors = ["Composable Developers"]
edition = "2021"
homepage = "https://composable.finance"
name = "cosmwasm-rpc"
rust-version = "1.56"
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# substrate primitives
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407" }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407" }

# local
cosmwasm-runtime-api = { workspace = true }

# SCALE
codec = { package = "parity-scale-codec", version = "3.6", default-features = false, features = [
    "derive",
] }

# rpc
jsonrpsee = { version = "0.22.5", features = ["client", "server", "macros"] }
