[package]
name = "np-runtime"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noir-protocol/noir/"

[dependencies]
array-bytes = { workspace = true, optional = true }
base64ct = { workspace = true, optional = true }
codec = { workspace = true, package = "parity-scale-codec", features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true }
serde = { workspace = true, optional = true }

# noir
np-crypto = { workspace = true }
np-io = { workspace = true }

# substrate
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-runtime-interface = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"array-bytes",
	"base64ct/std",
	"codec/std",
	"scale-info/std",
	"serde",
	"np-crypto/std",
	"np-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
