[package]
name = "solana-runtime-api"
license = "Apache-2.0"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
bincode = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
nostd = { workspace = true, features = ["alloc"] }
pallet-solana = { workspace = true, default-features = false }
parity-scale-codec = { workspace = true, default-features = false, features = [
    "derive",
] }
scale-info = { workspace = true, default-features = false, features = [
    "derive",
] }
serde = { workspace = true, default-features = false }
solana-compute-budget = { workspace = true, default-features = false }
solana-inline-spl = { workspace = true, default-features = false }
solana-rpc-client-api = { workspace = true, default-features = false }
solana-sdk = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
    "bincode/std",
    "frame-support/std",
    "pallet-solana/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "serde/std",
    "solana-compute-budget/std",
    "solana-inline-spl/std",
    "solana-rpc-client-api/std",
    "solana-sdk/std",
    "sp-api/std",
]
