[package]
name = "solana-runtime-api"
version = "0.4.0"
authors = ["Haderech Pte. Ltd."]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noirhq/noir.git"
publish = false

[dependencies]
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2409", default-features = false }
np-solana = { workspace = true, default-features = false }
parity-scale-codec = { version = "3.6", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2.11", default-features = false, features = [
    "derive",
] }

[features]
default = ["std"]
std = [
    "sp-api/std",
    "np-solana/std",
    "parity-scale-codec/std",
    "scale-info/std",
]
