[package]
name = "cosmos-runtime-api"
version = "0.4.0"
authors = ["Haderech Pte. Ltd."]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noirhq/noir.git"
publish = false

[dependencies]
nostd = { workspace = true }
pallet-cosmos-types = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
sp-api = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"nostd/std",
	"pallet-cosmos-types/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	"sp-runtime/std",
]
