[package]
name = "cosmos-runtime-api"
license = "Apache-2.0"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
nostd = { workspace = true }
pallet-cosmos-types = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
sp-api = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"nostd/std",
	"pallet-cosmos-types/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	"sp-runtime/std",
]
