[package]
name = "pallet-cosmos-x-bank"
license = "Apache-2.0"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
cosmos-sdk-proto = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
nostd = { workspace = true }
pallet-cosmos = { workspace = true }
pallet-cosmos-types = { workspace = true }
pallet-cosmos-x-bank-types = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
    "cosmos-sdk-proto/std",
    "frame-support/std",
    "frame-system/std",
    "nostd/std",
    "pallet-cosmos/std",
    "pallet-cosmos-types/std",
    "pallet-cosmos-x-bank-types/std",
    "sp-core/std",
    "sp-runtime/std",
]
