[package]
name = "pallet-cosmos-x-auth-signing"
license = "GPL-3.0-or-later"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
cosmos-sdk-proto = { workspace = true, features = ["cosmwasm"] }
nostd = { workspace = true }
pallet-cosmos-types = { workspace = true }
pallet-cosmos-x-auth-migrations = { workspace = true }
pallet-cosmos-x-bank-types = { workspace = true }
pallet-cosmos-x-wasm-types = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
base64 = { workspace = true, features = ["std"] }
const-hex = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	"cosmos-sdk-proto/std",
	"nostd/std",
	"pallet-cosmos-types/std",
	"pallet-cosmos-x-auth-migrations/std",
	"pallet-cosmos-x-bank-types/std",
	"pallet-cosmos-x-wasm-types/std",
	"serde_json/std",
]
