[package]
name = "pallet-solana"
description = "FRAME solana to process Solana transactions"
license = "GPL-3.0-or-later"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false
